# 1.Create a 3x3x3 array with random values

In [6]:
import numpy as np


random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.93080889 0.09793034 0.51715472]
  [0.08042211 0.1975002  0.23146289]
  [0.87425821 0.79553317 0.21180515]]

 [[0.0672507  0.32865345 0.11730862]
  [0.42227324 0.3954187  0.71172767]
  [0.87666582 0.35462431 0.64217857]]

 [[0.58379833 0.89226793 0.6922576 ]
  [0.43688498 0.06023474 0.11957109]
  [0.95289897 0.10754607 0.54604982]]]


# 2.Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

In [7]:
import numpy as np


matrix = np.zeros((5, 5))


for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
import numpy as np


matrix = np.zeros((8, 8), dtype=int)


matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4.Normalize a 5x5 random matrix

In [9]:
import numpy as np

random_matrix = np.random.rand(5, 5)


mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)


normalized_matrix = (random_matrix - mean_value) / std_deviation

print("Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Random Matrix:
[[0.51498377 0.60727186 0.70508158 0.48018897 0.09439686]
 [0.20795773 0.65274469 0.62679036 0.88792274 0.92743997]
 [0.34366833 0.42642359 0.43705567 0.017069   0.71799983]
 [0.33645457 0.7897146  0.83651065 0.34829655 0.42330992]
 [0.26130917 0.7905109  0.52267314 0.34281797 0.98256183]]

Normalized Matrix:
[[-0.06390434  0.29874872  0.68309944 -0.20063314 -1.71663249]
 [-1.27038645  0.47743766  0.37544814  1.40158763  1.55687358]
 [-0.73710134 -0.41190828 -0.37012872 -2.02049821  0.73386267]
 [-0.76544837  1.01567132  1.19955992 -0.71891441 -0.42414368]
 [-1.06073793  1.01880042 -0.03368837 -0.74044291  1.77347913]]


# 5.How to find common values between two arrays in Numpy in Python?

In [11]:
import numpy as np


array1 = np.array([11, 22, 24, 10, 9])
array2 = np.array([22, 9, 10, 6, 7])


common_values = np.intersect1d(array1, array2)

print("Common Values:", common_values)

Common Values: [ 9 10 22]


# 6.How to get the dates of yesterday,today and tomorrow?

In [1]:
import numpy as np
from datetime import datetime, timedelta


today = datetime.today().date()


yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)


dates = np.array([yesterday, today, tomorrow])

print("Dates as NumPy array:", dates)


Dates as NumPy array: [datetime.date(2023, 9, 20) datetime.date(2023, 9, 21)
 datetime.date(2023, 9, 22)]


# 7.Consider two random arrays A and B, check if they are equal

In [2]:
import numpy as np


A = np.array([2, 4, 5])
B = np.array([2, 4, 5])


if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are equal.


# 8.Create a random vector of size 10 and replace the maximum value by 0

In [3]:
import numpy as np


random_vector = np.random.rand(10)


max_index = np.argmax(random_vector)


random_vector[max_index] = 0

print(random_vector)


[0.43803755 0.16014809 0.6357019  0.49598552 0.00315471 0.59134272
 0.06119627 0.         0.68451458 0.09021947]


# 9.How to print all the values of an array

In [4]:
import numpy as np


arr_2d = np.array([[4, 1, 8],
                   [9, 20, 11],
                   [8, 2, 3]])


for row in arr_2d:
    for val in row:
        print(val)
        

4
1
8
9
20
11
8
2
3


# 10.Subtract the mean of each row of a matrix

In [5]:
import numpy as np


matrix = np.array([[4, 1, 8],
                   [9, 20, 11],
                   [8, 2, 3]])

# Calculate the mean of each ro
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the original matrix using broadcasting
matrix_minus_mean = matrix - row_means

# Print the result
print(matrix_minus_mean)

[[-0.33333333 -3.33333333  3.66666667]
 [-4.33333333  6.66666667 -2.33333333]
 [ 3.66666667 -2.33333333 -1.33333333]]


# 11.Consider a given vector. How to add one to each element indexed by a second vector(be careful with repeated indices)? 

In [12]:
import numpy as np

# Your initial vector
initial_vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
indices = np.array([0, 2, 3])

# Create a new vector to store the results
result_vector = initial_vector.copy()

# Add one to each element at the specified indices
result_vector[indices] += 1

print(result_vector)


[2 2 4 5 5]


# 12.How to get the diagonal of a dot product ?

In [13]:
import numpy as np

# Create two matrices A and B
A = np.array([[4, 1, 8],
             [9, 20, 11],
             [8, 2, 3]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculate the dot product of A and B
dot_product = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)


[ 66 194  67]


# 13.How to Find the Most Frequent Value in an array?

In [15]:
import numpy as np

# Sample array
my_array = np.array([0,10,50])

# Use the `unique` function to get unique values and their counts
unique_values, counts = np.unique(my_array, return_counts=True)

# Find the index of the maximum count, which corresponds to the most frequent value
most_frequent_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[most_frequent_index]

print(f"The most frequent value is {most_frequent_value} with {counts[most_frequent_index]} occurrences.")

The most frequent value is 0 with 1 occurrences.


# 14.How to get the n-largest values of an array?

In [17]:
import numpy as np

# Create an example array
arr = np.array([22, 8, 10, 9, 2, 6])

# Set the value of 'n' to get the n-largest values
n = 2

# Use partition to get the n-largest values
n_largest = np.partition(arr, -n)[-n:]

print(n_largest)


[10 22]


# 15.How to create a record array from a regular array?

In [19]:
import numpy as np

# Create a regular NumPy array
regular_array = np.array([11, 22, 33, 44, 55])

# Create a record array from the regular array
record_array = np.rec.array(regular_array, dtype=[('my_column', int)])

# Access data using column names
print("Record Array:")
print(record_array)
print("Accessing 'my_column':", record_array.my_column)

Record Array:
[(11,) (22,) (33,) (44,) (55,)]
Accessing 'my_column': [11 22 33 44 55]


# 16.How to swap two rows of an array ?

In [22]:
import numpy as np

# Create a sample 2D NumPy array
array = np.array([[4, 1, 8],
                 [9, 20, 11],
                 [8, 2, 3]])

# Swap rows (for example, swapping rows 0 and 2)
array[[0, 2]] = array[[2, 0]]

# Now, 'array' will have rows 0 and 2 swapped
print(array)

[[ 8  2  3]
 [ 9 20 11]
 [ 4  1  8]]


# 17. Write a python code to reshape to the next dimension of numpy array

In [21]:
import numpy as np

# Create a NumPy array
original_array = np.array([[2, 3], [4, 5], [6, 7]])

# Reshape the array to the next dimension
reshaped_array = original_array.reshape(-1, original_array.shape[0])

# Print the original and reshaped arrays
print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[[2 3]
 [4 5]
 [6 7]]

Reshaped Array:
[[2 3 4]
 [5 6 7]]


In [23]:
import numpy as np

olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# 1. Find Country index with max gold

In [24]:
import numpy as np

# Define the data
olympic_country = np.array(['GBR', 'Chine', 'RUS', 'US', 'KOR, JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Find the index of the country with the maximum gold medals
max_gold_index = np.argmax(olympic_country_gold)

# Get the country with the maximum gold medals
country_with_max_gold = olympic_country[max_gold_index]

print(f"The country with the maximum gold medals is {country_with_max_gold} at index {max_gold_index}.")

The country with the maximum gold medals is US at index 3.


# 2. Country with Max Gold

In [25]:
import numpy as np

# Assuming you have the data stored in the following arrays
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Find the index of the country with the max gold medals
max_gold_index = np.argmax(olympic_country_gold)

# Get the country with the max gold medals
country_with_max_gold = olympic_country[max_gold_index]

print("Country with the most gold medals:", country_with_max_gold)

Country with the most gold medals: US


# 3. Find Countries with More than 20 Gold

In [26]:
import numpy as np

# Assuming you have the data stored in the following arrays
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Create a boolean mask for countries with more than 20 gold medals
mask = olympic_country_gold > 20

# Use the mask to filter the countries
countries_with_more_than_20_gold = olympic_country[mask]

print("Countries with more than 20 gold medals:", countries_with_more_than_20_gold)

Countries with more than 20 gold medals: ['GBR' 'China' 'RUS' 'US']


# 4. Evaluate the dataset and print the medal:

1. print each country name with number of gold medals

2. print each country nale with total number of medals

In [27]:
import numpy as np

# Assuming you have the data stored in the following arrays
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# Calculate and print each country's name with the number of gold medals and total medals
for i in range(len(olympic_country)):
    country = olympic_country[i]
    gold = olympic_country_gold[i]
    silver = olympic_country_silver[i]
    bronze = olympic_country_bronze[i]
    total_medals = gold + silver + bronze
    print(f"Country: {country}, Gold Medals: {gold}, Total Medals: {total_medals}")

Country: GBR, Gold Medals: 29, Total Medals: 65
Country: China, Gold Medals: 38, Total Medals: 88
Country: RUS, Gold Medals: 24, Total Medals: 81
Country: US, Gold Medals: 46, Total Medals: 103
Country: KOR, Gold Medals: 13, Total Medals: 28
Country: JPN, Gold Medals: 7, Total Medals: 38
Country: GER, Gold Medals: 11, Total Medals: 36
